name: "Can I deploy to a tagged environment?"
description: "Checks current participants with this tag are compatible with your latest version"
branding:
  icon: "check"
  color: "green"
inputs:
  pact_broker:
    description: "The url of your pact broker"
    required: true
  pact_broker_token:
    description: "Your pact broker token"
    required: true
  participant_name:
    description: "The name of your participant (usually project name)"
    required: true
  version:
    description: "The version of your participant (defaults to latest)"
    required: false
  latest:
    description: "The latest tag value of your participant (i.e. 'test' or 'stage')"
    required: false
  to:
    description: "The tag you wish to deploy to (test / stage / prod etc...)"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
