name: "Can I deploy to a tagged environment?"
description: "Checks current participants with this tag are compatible with your new one"
branding:
  icon: "check"
  color: "green"
inputs:
  participant_name:
    description: "The name of your participant (usually project name)"
    required: true
  target_tag:
    description: "The tag you wish to check (test / stage / prod etc...)"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/canideployTo.sh
      shell: bash
